title: Networking Charms
description: My Personal Networking Blog
author: Emanuele Mazza
github: https://github.com/emanuelemazza
about: I work as a network specialist at Google Cloud.
disqus_shortname:
google_analytics:
avatar_url: /static/img/emazza.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    # - icon: fa-facebook
    #   link: "#"
    # - icon: fa-twitter
    #   link: "#"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/emanuelemazza/"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/emanuelemazza"

share:
  twitter_username:
  fb_appid:

urls:
    - text: About Me
      url: /about/
    # - text: My Projects
    #   url: /projects/
    # - text: XML Feed
    #   url: /feed.xml

url: "https://emanuelemazza.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
